version: '3.8'
services:
  api:
    build: .
    volumes:
      - .:/app
    ports:
      - "8080:80"
  webmap:
    build: ./webmap
    ports:
      - "8081:80"
    depends_on:
      - api
  nginx:
    image: nginx:1.21
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8082:80"
    depends_on:
      - webmap
      - api

